araise-dev/CrudBundle

docs/extensions/menu.md, src/Resources/views/extensions/knp_menu_sub.html.twig
=> feat: make icon of sub menu changeable

src/Controller/CrudController.php, src/Definition/AbstractDefinition.php
Depends on https://github.com/araise-dev/TableBundle/pull/5
=> feat(batch-actions): moved to table-bundle

src/Builder/DefinitionMenuBuilder.php, src/Controller/CrudController.php, src/Definition/AbstractDefinition.php, src/Definition/DefinitionInterface.php, src/Resources/views/Crud/create.html.twig, src/Resources/views/Crud/edit.html.twig, src/Resources/views/Crud/show.html.twig, src/Resources/views/includes/main/_site_title.html.twig
=> Separate title in two lines and refactor definition a bit

src/Controller/CrudController.php
The issue you found on the CREATE page
=> Add title (including meta) to CREATE page

src/Resources/assets/controllers/tab_controller.js, src/Resources/views/includes/layout/_block.html.twig
=> feat(tab): restyle active tab items

src/Definition/AbstractDefinition.php
Getter for an single action / batchAction. 
Quality of life.
=> feat: add a getter for a single action

docs/table-configuration.md
Update the documentation of the table configuration:
- Remove task in the documentation
- Update filter configuration
- Update action configuration
=> docs: remove task and update action and filter descriptions

composer.json, src/Definition/AbstractDefinition.php, src/Formatter/CrudDefaultFormatter.php, src/Twig/ToStringExtension.php
Remove unused coduo/php-to-string dependency and use CoreBundle-implementation
=> Feature/23 Remove StringConverter dependency

docs/cookbook/custom_actions.md
Addendum to https://github.com/araise-dev/CrudBundle/pull/19
=> docs: add documentation for actions overflow

src/Resources/views/includes/layout/_block.html.twig
=> Only show title inside BlockBlock when set

src/Resources/views/includes/layout/_content.html.twig
Apply Helper Function to Relationship Fields
=> Small action buttons

src/Resources/views/extensions/knp_menu_main.html.twig
Improve styling in menu for better hierarchy
=> Menu hierarchy

src/Resources/assets/controllers/tooltip_controller.js
Add some basic options for tooltip controller
=> Basic options for tooltip controller

src/Action/DropdownAction.php, src/Resources/views/includes/topbar/_actions.html.twig
Ref: https://github.com/araise-dev/CoreBundle/pull/23
=> feat: Add dropdown action

src/Content/RelationContent.php, src/Controller/CrudController.php, src/Definition/DefinitionInterface.php
In relation with: https://github.com/araise-dev/TableBundle/pull/48
=> Fix export for relation content

src/Resources/views/base.html.twig
References: https://dev.whatwedo.ch/araise/araise-meta/-/issues/29
Move footer to the right side and use same font color as in the footer of the demo websites
=> feat: move footer to the right hand side

docs/index.html
References: https://dev.whatwedo.ch/araise/araise-meta/-/issues/24
=> docs: change theme of mermaid diagrams

src/Resources/views/form_layout.html.twig
References: https://dev.whatwedo.ch/araise/araise-meta/-/issues/69
=> fix: use proper spacing for MoneyType

src/Definition/AbstractDefinition.php, src/View/DefinitionView.php
References: https://dev.whatwedo.ch/araise/araise-meta/-/issues/125
=> feat: add a way to change out the main form type

src/Resources/views/includes/layout/_content.html.twig
In combination with https://github.com/araise-dev/CoreBundle/pull/32
=> Improve link styling (Meta #99)

src/Resources/views/includes/layout/_content.html.twig
Belongs to https://github.com/araise-dev/TableBundle/pull/63
=> Move content to table header (Meta #119)

src/Resources/views/form_layout.html.twig, src/Resources/views/includes/topbar/_actions.html.twig
- https://github.com/araise-dev/CoreBundle/pull/38
- Sample health project (Gitlab)
=> Different related improvements

src/Resources/views/extensions/knp_menu_main.html.twig
Related Pull Request here:
https://github.com/araise-dev/CoreBundle/pull/41
=> Refactor badge for menu item to include utility classes
